server:
  port: ${LINCE_KVS_PORT:8080}

spring:
  jackson:
    default-property-inclusion: non_null

  datasource:
    url: ${LINCE_KVS_DATASOURCE_URL:jdbc:h2:mem:example}
    platform: ${LINCE_KVS_DATASOURCE_PLATFORM:h2}
