server:
  port: ${LINCE_KVS_PORT:8080}

spring:
  application:
    name: @project.artifactId@

  profiles:
    include: management

  jackson:
    default-property-inclusion: non_null
    time-zone: America/Sao_Paulo

  datasource:
    url: ${LINCE_KVS_DATASOURCE_URL:jdbc:mysql://lincemysql:3306/lincekvs}
    username: ${LINCE_KVS_DATASOURCE_USER:lincekvs}
    password: ${LINCE_KVS_DATASOURCE_PASS:lincepass}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    work:
      lince: WARN
