server:
  port: ${LINCE_KVS_PORT:8080}

spring:
  application:
    name: @project.artifactId@

  profiles:
    include: management

  jackson:
    default-property-inclusion: non_null
    time-zone: America/Sao_Paulo

  datasource:
    url: ${LINCE_KVS_DATASOURCE_URL:jdbc:h2:mem:lince-db}
    platform: ${LINCE_KVS_DATASOURCE_PLATFORM:h2}

  jpa:
    hibernate:
      ddl-auto: update


logging:
  level:
    work:
      lince: WARN
