server:
  port: ${LINCE_KVS_PORT:8080}

spring:
  jackson:
    default-property-inclusion: non_null

  datasource:
    url: ${LINCE_KVS_DATASOURCE_URL:jdbc:h2:file:~\.h2\lince-kvs}
    platform: ${LINCE_KVS_DATASOURCE_PLATFORM:h2}
  jpa:
    hibernate:
      ddl-auto: update

management:

  endpoints:
    web:
      base-path: /internal
      exposure:
        include: "*"
  info:
    git:
      mode: full

info:
  app:
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

  lince:
    hostname: ${HOSTNAME:lince-kvs-host}
    commons:
      health:
        serviceGroup: @project.groupId@
        serviceName: @project.artifactId@
        serviceVersion: @project.version@

logging:
  level:
    work:
      lince: WARN